---
kind: pipeline
name: default

clone:

steps:
  - name: build
    image: node:18-bullseye-slim
    commands:
      - npm install
      - npm run build

  - name: deployment
    image: joomlaprojects/docker-images:packager
    depends_on:
      - build
    environment:
      REMOTE_PRIVATE_KEY:
        from_secret: REMOTE_PRIVATE_KEY
      developer_host:
        from_secret: developer_host
      sftp_user:
        from_secret: sftp_user
    commands:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$REMOTE_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create server sftp host $developer_host user $sftp_user port 22
      - rclone -v sync build server:public_html

---
kind: signature
hmac: c70c88470b45a1c1fc9aef1d98c685115d7ddf693223c22839ef25c485d46f07

...
